input_folder_path: ./model
output_file_path: ./generated
module_name: github.com/joeriddles/goalesce/examples/custom_controller
models_package: github.com/joeriddles/goalesce/examples/custom_controller/model
query_package: github.com/joeriddles/goalesce/examples/custom_controller/query
clear_output_dir: true
user_templates:
  controller.tmpl: ./custom_controller.tmpl
