input_folder_path: ./model
output_file_path: ./generated
module_name: github.com/joeriddles/goalesce/examples/multiple_files
models_package: github.com/joeriddles/goalesce/examples/multiple_files/model
query_package: github.com/joeriddles/goalesce/examples/multiple_files/query
clear_output_dir: true
