input_folder_path: ./model
output_file_path: ./generated
module_name: github.com/joeriddles/goalesce/examples/echo
models_package: github.com/joeriddles/goalesce/examples/echo/model
query_package: github.com/joeriddles/goalesce/examples/echo/query
clear_output_dir: true
prune_yaml: true

server_codegen:
  package: api
  output: ./generated/server_gen.go
  generate:
    echo-server: true
    strict-server: true
    embedded-spec: true
