openapi: 3.0.3
info:
  title: Hello YAML
  version: 1.0.0
  description: A simple CRUD API made Go
paths:
  /:
    get:
      summary: Get 'em
      parameters:
        - name: who
          in: query
          required: true
          schema:
            type: string
            description: Who to get
            enum:
              - joe
              - "not joe"
      responses:
        200:
          description: OK
