input_folder_path: "./"
output_file_path: "./generated/exclude"
module_name: "github.com/joeriddles/gorm-oapi-codegen/examples/exclude"
models_package: "github.com/joeriddles/gorm-oapi-codegen/examples/exclude"
clear_output_dir: true
exclude_models:
  - Manufacturer
  - Model
