input_folder_path: ./model
output_file_path: ./generated
module_name: github.com/joeriddles/goalesce/examples/circular
models_package: github.com/joeriddles/goalesce/examples/circular/model
query_package: github.com/joeriddles/goalesce/examples/circular/query
allow_custom_models: true
clear_output_dir: true
